name: fx_network
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  build_runner: ^2.4.6
  dio: ^5.3.2
  dio_smart_retry: ^5.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  http: ^1.1.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  pretty_dio_logger: ^1.3.1


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.6.0
  mockito: ^5.4.2

flutter:
